name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.16'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit app
        env:
          GCP_API_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          echo "Running Streamlit app..."
          streamlit run 💧_AguaTierra.py

